{% set name = "covdefaults" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/covdefaults-{{ version }}.tar.gz
  sha256: e543862ee0347769b47b27fa586d690e6b91587a3dcaaf8552fcfb1fac03d061

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - coverage >=6.0.2
    - python >=3.6

test:
  imports:
    - covdefaults
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asottile/covdefaults
  summary: A coverage plugin to provide sensible default settings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
