{% set name = "covdefaults" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/covdefaults-{{ version }}.tar.gz
  sha256: 4e99f679f12d792bc62e5510fa3eb59546ed47bd569e36e4fddc4081c9c3ebf7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - coverage >=6.0.2
    - python >={{ python_min }}

test:
  imports:
    - covdefaults
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asottile/covdefaults
  summary: A coverage plugin to provide sensible default settings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
